"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import mdc-gui

# Implementing MainFrame
class MainFrame( mdc-gui.MainFrame ):
	def __init__( self, parent ):
		mdc-gui.MainFrame.__init__( self, parent )
	
