"""Subclass of MultiPing, which is generated by wxFormBuilder."""

import wx
import mdc_gui

# Implementing MultiPing
class MultiPing( mdc_gui.MultiPing ):
	def __init__( self, parent ):
		mdc_gui.MultiPing.__init__( self, parent )
	
